namespace DroneStream.Models;

// This model represents dynamic telemetry data generated by the drone.
public class DroneTelemetry
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid DroneId { get; set; }
}