using System.Text.Json.Serialization;

namespace backend.Models;




// This model represents dynamic telemetry data generated by the drone.
public class DroneTelemetry
{
    public Guid DroneId { get; set; }

    // Frame capture moment
    public string? Timestamp { get; set; }

    // Geolocation
    public double? Latitude { get; set; }
    public double? Longitude { get; set; }
    public double? RelativeAltitude { get; set; }
    public double? AbsoluteAltitude { get; set; }

    // Camera orientation
    public double? GimbalYaw { get; set; }
    public double? GimbalPitch { get; set; }
    public double? GimbalRoll { get; set; }

    [JsonPropertyName("gateway")]
    public string SerialNumber { get; set; } = string.Empty;
}